export const LIST_MANGA = {
  newManga: [
    {
      id: 1,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/ou5W1h1xAEIPMEWWCmGldN4CpnC.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 2,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/ou5W1h1xAEIPMEWWCmGldN4CpnC.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 3,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/ou5W1h1xAEIPMEWWCmGldN4CpnC.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 4,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/ou5W1h1xAEIPMEWWCmGldN4CpnC.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 5,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/ou5W1h1xAEIPMEWWCmGldN4CpnC.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 6,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/ou5W1h1xAEIPMEWWCmGldN4CpnC.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 7,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/ou5W1h1xAEIPMEWWCmGldN4CpnC.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 8,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/ou5W1h1xAEIPMEWWCmGldN4CpnC.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 9,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/ou5W1h1xAEIPMEWWCmGldN4CpnC.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 10,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/ou5W1h1xAEIPMEWWCmGldN4CpnC.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
  ],
  hotManga: [
    {
      id: 1,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/xeg0UhMmzSalvyK7kvhTHcKXIf8.jpg',
      title: 'Thor: Tình Yêu và Sấm Sét',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 2,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/xeg0UhMmzSalvyK7kvhTHcKXIf8.jpg',
      title: 'Thor: Tình Yêu và Sấm Sét',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 3,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 4,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/xeg0UhMmzSalvyK7kvhTHcKXIf8.jpg',
      title: 'Thor: Tình Yêu và Sấm Sét',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 5,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/xeg0UhMmzSalvyK7kvhTHcKXIf8.jpg',
      title: 'Thor: Tình Yêu và Sấm Sét',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 6,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/xeg0UhMmzSalvyK7kvhTHcKXIf8.jpg',
      title: 'Thor: Tình Yêu và Sấm Sét',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
  ],
  allManga: [
    {
      id: 1,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 2,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 3,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 4,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 5,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 6,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 7,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 8,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 9,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
    {
      id: 10,
      img: 'https://www.themoviedb.org/t/p/w220_and_h330_face/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
      title: 'Chúa Tể Của Những Chiếc Nhẫn: Những Chiến Nhẫn Toàn Năng',
      description: 'Đây là mô tả',
      views: '72N',
      auth: 'Fujitora',
      numChapter: 12,
      time: '10 ngày trước',
    },
  ],
};
