export const LIST_FILM = {
  newFilm: [
    {
      id: 1,
      img: 'https://i.ytimg.com/vi/5siNvZgGb7o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBolyqAJltGtNb-2o-SOBAVlDAPIA',
      title: 'Anh khoa có cùng đồng bọn đi thanh toán băng đảng xã hội đen',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Rambo',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '10 ngày trước',
    },
    {
      id: 2,
      img: 'https://i.ytimg.com/vi/5siNvZgGb7o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBolyqAJltGtNb-2o-SOBAVlDAPIA',
      title: 'Anh khoa có cùng đồng bọn đi thanh toán băng đảng xã hội đen',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Rambo 2',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '10 ngày trước',
    },
    {
      id: 3,
      img: 'https://i.ytimg.com/vi/5siNvZgGb7o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBolyqAJltGtNb-2o-SOBAVlDAPIA',
      title: 'Anh khoa có cùng đồng bọn đi thanh toán băng đảng xã hội đen',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Rambo 3',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '10 ngày trước',
    },
    {
      id: 4,
      img: 'https://i.ytimg.com/vi/5siNvZgGb7o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBolyqAJltGtNb-2o-SOBAVlDAPIA',
      title: 'Anh khoa có cùng đồng bọn đi thanh toán băng đảng xã hội đen',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Rambo 4',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '10 ngày trước',
    },
    {
      id: 5,
      img: 'https://i.ytimg.com/vi/5siNvZgGb7o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBolyqAJltGtNb-2o-SOBAVlDAPIA',
      title: 'Anh khoa có cùng đồng bọn đi thanh toán băng đảng xã hội đen',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Rambo 5',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '10 ngày trước',
    },
    {
      id: 6,
      img: 'https://i.ytimg.com/vi/5siNvZgGb7o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBolyqAJltGtNb-2o-SOBAVlDAPIA',
      title: 'Anh khoa có cùng đồng bọn đi thanh toán băng đảng xã hội đen',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Rambo 6',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '10 ngày trước',
    },
    {
      id: 7,
      img: 'https://i.ytimg.com/vi/5siNvZgGb7o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBolyqAJltGtNb-2o-SOBAVlDAPIA',
      title: 'Anh khoa có cùng đồng bọn đi thanh toán băng đảng xã hội đen',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Rambo 7',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '10 ngày trước',
    },
    {
      id: 8,
      img: 'https://i.ytimg.com/vi/5siNvZgGb7o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBolyqAJltGtNb-2o-SOBAVlDAPIA',
      title: 'Anh khoa có cùng đồng bọn đi thanh toán băng đảng xã hội đen',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Rambo 8',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '10 ngày trước',
    },
    {
      id: 9,
      img: 'https://i.ytimg.com/vi/5siNvZgGb7o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBolyqAJltGtNb-2o-SOBAVlDAPIA',
      title: 'Anh khoa có cùng đồng bọn đi thanh toán băng đảng xã hội đen',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Rambo 9',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '10 ngày trước',
    },
    {
      id: 10,
      img: 'https://i.ytimg.com/vi/5siNvZgGb7o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBolyqAJltGtNb-2o-SOBAVlDAPIA',
      title: 'Anh khoa có cùng đồng bọn đi thanh toán băng đảng xã hội đen',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Rambo 10',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '10 ngày trước',
    },
  ],
  hotFilm: [
    {
      id: 1,
      img: 'https://i.ytimg.com/vi/GYeGcLaM0wY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBR-h0HonskS6angL1DON-kwTFLrw',
      title: 'Xếp đá cùng bố Độ',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Mixi',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '2 ngày trước',
    },
    {
      id: 2,
      img: 'https://i.ytimg.com/vi/GYeGcLaM0wY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBR-h0HonskS6angL1DON-kwTFLrw',
      title: 'Xếp đá cùng bố Độ',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Mixi 2',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '2 ngày trước',
    },
    {
      id: 3,
      img: 'https://i.ytimg.com/vi/GYeGcLaM0wY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBR-h0HonskS6angL1DON-kwTFLrw',
      title: 'Xếp đá cùng bố Độ',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Mixi 3',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '2 ngày trước',
    },
    {
      id: 4,
      img: 'https://i.ytimg.com/vi/GYeGcLaM0wY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBR-h0HonskS6angL1DON-kwTFLrw',
      title: 'Xếp đá cùng bố Độ',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Mixi 4',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '2 ngày trước',
    },
    {
      id: 5,
      img: 'https://i.ytimg.com/vi/GYeGcLaM0wY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBR-h0HonskS6angL1DON-kwTFLrw',
      title: 'Xếp đá cùng bố Độ',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Mixi 5',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '2 ngày trước',
    },
    {
      id: 6,
      img: 'https://i.ytimg.com/vi/GYeGcLaM0wY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBR-h0HonskS6angL1DON-kwTFLrw',
      title: 'Xếp đá cùng bố Độ',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Mixi 6',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '2 ngày trước',
    },
  ],
  allFilm: [
    {
      id: 1,
      img: 'https://i.ytimg.com/vi/OWW90u9eaXY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXGWElRPQn1Yl2vzPdUcVkwws4Mw',
      title: 'Bô khoe nhà mới',
      description:'Đây là mô tả',
      views: '2N',
      auth: 'Độ Mixi',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '12 ngày trước',
    },
    {
      id: 2,
      img: 'https://i.ytimg.com/vi/OWW90u9eaXY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXGWElRPQn1Yl2vzPdUcVkwws4Mw',
      title: 'Bô khoe nhà mới',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Độ Mixi',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '12 ngày trước',
    },
    {
      id: 3,
      img: 'https://i.ytimg.com/vi/OWW90u9eaXY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXGWElRPQn1Yl2vzPdUcVkwws4Mw',
      title: 'Bô khoe nhà mới',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Độ Mixi',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '12 ngày trước',
    },
    {
      id: 4,
      img:'https://i.ytimg.com/vi/OWW90u9eaXY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXGWElRPQn1Yl2vzPdUcVkwws4Mw',
      title: 'Bô khoe nhà mới',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Độ Mixi',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '12 ngày trước',
    },
    {
      id: 5,
      img: 'https://i.ytimg.com/vi/OWW90u9eaXY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXGWElRPQn1Yl2vzPdUcVkwws4Mw',
      title: 'Bô khoe nhà mới',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Độ Mixi',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '12 ngày trước',
    },
    {
      id: 6,
      img: 'https://i.ytimg.com/vi/OWW90u9eaXY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXGWElRPQn1Yl2vzPdUcVkwws4Mw',
      title: 'Bô khoe nhà mới',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Độ Mixi',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '12 ngày trước',
    },
    {
      id: 7,
      img: 'https://i.ytimg.com/vi/OWW90u9eaXY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXGWElRPQn1Yl2vzPdUcVkwws4Mw',
      title: 'Bô khoe nhà mới',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Độ Mixi',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '12 ngày trước',
    },
    {
      id: 8,
      img: 'https://i.ytimg.com/vi/OWW90u9eaXY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXGWElRPQn1Yl2vzPdUcVkwws4Mw',
      title: 'Bô khoe nhà mới',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Độ Mixi',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '12 ngày trước',
    },
    {
      id: 9,
      img: 'https://i.ytimg.com/vi/OWW90u9eaXY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXGWElRPQn1Yl2vzPdUcVkwws4Mw',
      title: 'Bô khoe nhà mới',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Độ Mixi',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '12 ngày trước',
    },
    {
      id: 10,
      img: 'https://i.ytimg.com/vi/OWW90u9eaXY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXGWElRPQn1Yl2vzPdUcVkwws4Mw',
      title: 'Bô khoe nhà mới',
      description:'Đây là mô tả',
      views: '72N',
      auth: 'Độ Mixi',
      linkVideo: 'https://www.youtube.com/watch?v=sxtn09rY7_w',
      time: '12 ngày trước',
    },
  ]
};
